version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db_test
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node:
    image: node:14
    container_name: node_app_test
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: ["npm", "start"]

volumes:
  mongo_data:
